router bgp 65100
  bgp bestpath as-path multipath-relax
  no bgp ebgp-requires-policy
  bgp router-id 10.13.37.1
  neighbor BGP-TALOS-01 peer-group
  neighbor BGP-TALOS-01 remote-as external
  neighbor BGP-TALOS-01 timers 3 9
  neighbor 10.0.100.11 peer-group BGP-TALOS-01
  neighbor 10.0.100.12 peer-group BGP-TALOS-01
  neighbor 10.0.100.13 peer-group BGP-TALOS-01
  neighbor 10.0.100.21 peer-group BGP-TALOS-01
  neighbor 10.0.100.22 peer-group BGP-TALOS-01
  neighbor 10.0.100.23 peer-group BGP-TALOS-01
